---

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push container image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker Image
        run: docker build . -t ghcr.io/the-openplatform/frontend:latest --target production
      - name: Push the Docker Image
        run: docker push ghcr.io/the-openplatform/frontend:latest

